name: berkania
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# ------------------------------------------------------ #

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.5

  # ICONS
  iconsax: ^0.0.8

  # MULTIPLE LANGUAGES
  flutter_localization: ^0.2.0

  # MAP
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  custom_info_window: ^1.0.1
  http: ^1.2.0

  # DI
  get_it: ^7.7.0

  # FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.3
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.17.1
  google_sign_in: ^6.2.1

  # NAVIGATION
  go_router: ^14.1.0

  # LOCAL STORAGE
  get_storage: ^2.1.1

  # ANIMATION
  lottie: ^3.1.0

  # NAVIGATE OUTSIDE THE APP
  url_launcher: ^6.2.6

  # CHECK NETWORK
  connectivity_plus: ^5.0.2

  # SPLASH SCREEN
  flutter_native_splash: ^2.3.8

  # SNACK BAR
  awesome_snackbar_content: ^0.1.3

  # IMAGE PICKER
  image_picker: ^1.0.0

  # DATE TIME
  date_picker_timeline: ^1.2.5

  # RATING
  flutter_rating_bar: ^4.0.1

# ------------------------------------------------------ #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/
  fonts:
    - family: Cal
      fonts:
        - asset: assets/fonts/Cal.otf