name: berkania
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # STATE MANAGEMENT
  flutter_bloc: ^8.1.5

  # ICONS
  iconsax: ^0.0.8

  # UTILITY
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.8
  go_router: ^14.1.0
  awesome_snackbar_content: ^0.1.3

  # MULTIPLE LANGUAGES
  flutter_localization: ^0.2.0

  # DI
  get_it: ^7.7.0

  # FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.7.3
  cloud_firestore: ^4.17.1

  # LOCAL STORAGE
  get_storage: ^2.1.1

  # MAP



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/icons/
    - assets/animations/
    - assets/images/
  fonts:
    - family: Cal
      fonts:
        - asset: assets/fonts/Cal.otf