// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe2dAM9J-8yRz5gD1TDwVa6_meRZ4m12E',
    appId: '1:757489769264:android:375024b9b9d104bb2806f5',
    messagingSenderId: '757489769264',
    projectId: 'limounareworked',
    storageBucket: 'limounareworked.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1pI_FPWAmyjjfO5AmTf94G7QxWXVr_k',
    appId: '1:757489769264:ios:7ae7de8d31ce378a2806f5',
    messagingSenderId: '757489769264',
    projectId: 'limounareworked',
    storageBucket: 'limounareworked.appspot.com',
    androidClientId: '757489769264-4jci58piujh9gbtjrbn0fnvq6cf8s2b9.apps.googleusercontent.com',
    iosClientId: '757489769264-4271hvndihen9t9stit59kshejm91sp3.apps.googleusercontent.com',
    iosBundleId: 'ma.agri.berkania',
  );
}
